database:
  host: localhost
  port: 5432
  user: your_db_user
  password: your_db_password
  name: fleet_management

rabbitmq:
  host: localhost
  port: 5672
  user: your_rabbitmq_user
  password: your_rabbitmq_password
  exchange: fleet.events
  queue: geofence_alerts

mqtt:
  broker: tcp://localhost:1883
  topic: /fleet/vehicle/{vehicle_id}/location

geofence:
  radius: 50
  center:
    latitude: -6.2088
    longitude: 106.8456